# Generated by Django 3.2.9 on 2021-11-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Episode', 'verbose_name_plural': 'Episodes'},
        ),
        migrations.AddField(
            model_name='episode',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='episode',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='guid',
            field=models.CharField(max_length=50, verbose_name='Guid'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.URLField(verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='link',
            field=models.URLField(verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='podcast_name',
            field=models.CharField(max_length=100, verbose_name='Podcast Name'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
